package:
   name: jade_utils
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..
git:
  depth: false

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
    - iris
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test --verbose

about:
  home: https://github.com/informaticslab/jade_utils
  license: BSD
  license_file: LICENSE
  summary: |
    Additional utilities to make Pangeo more useful.
